name: flutter_state_management_comparison
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.2
  http: ^1.1.2
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  
  flutter_lints: ^2.0.0



flutter:
  
  
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/story_persons/
    - assets/post_persons/
    - assets/posts/
    - assets/Instagram_logo.png
    - assets/Instagram_logo_mini.png


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
